[fontpackage]
########################################################################
# PACKAGE METADATA #####################################################
########################################################################

name = "Dedigama"
type = "family"
version = "Version 0.001; DEV; alpha"
status = "DEV" 
authors = ["mooniak"]
license = "	LvCL-0.1"
category = "text"
description = "Dedigama is a revival of the Sinhala typeface used by the Progress Publishers (Pragathi Publications) "
repository = { url = "https://github.com/mooniak/dedigama-libre-font", type = "git"}
homepage_url = "https://src.mooniak.com/dedigama-font/"
issues_url = "https://github.com/mooniak/dedigama-font/issues/" #OPTIONAL
funding_url = "https://opencollective.com/akuruxyz/projects/lanka-font-library"
foundry = { name = "mooniak", email = "hello@mooniak.com", url = "https://mooniak.com/", vendor_id = "MNIK" } #OPTIONAL:
designers = [ #OPTIONAL: Desiners from the nameID
  { name = "Damith Welikala", email = "kadira86@gmail.com", url = "" } ]

maintenance = { status = "actively-developed", comment = "" } #OPTIONAL: # `actively-developed`, `passively-maintained`, `as-is`, `experimental`, `looking-for-maintainer`, `deprecated`, and the default `none`,}
versions_provider = "tags" #REQUIERD: How is the font versions provided. When set to 'tags' the versions will be fetched from the git tags.

tools = "" #OPTIONAL: Details realted to font development and build. Similar to tools key in UFR METADATA.yml

progress = [ #OPTIONAL: Progress and of the project out of 100 percentage.
    { design = "50" },
    { family_styles = "100" },
    { character_set =  "60" },
    { drawing_quality =  "60" },
    { spacing =  "60"}, 
    { kerning =  "0"},
    { hinting =  "100" },
    { opentype_features =  "50" }, ]

########################################################################
# DISPLAY AND CLASSIFCATION DATA #######################################
########################################################################

tags = [ #OPTIONAL: Pakage specific display strings for display and testing purposes
    { style = "serif" }, # Blackletter, Calligraphic, Condensed, Decorative, Display, Handdrawn, Monospaced, Rounded, Sans-serif, Script, Serif, Slab, Stencil, Symbols"
    { contrast = "high" },
    { width =  "normal" },
    { body_height =  "normal" },
    { intended_useage =  "text"}, # large, medium, text, body, branding
    { figures =  "noraml"},
    { languages =  "si_LK" },
    { related_fonts =  "" }, ]

display_texts = [ #OPTIONAL: Pakage specific display strings for display and testing purposes
    { en_US = ""},
    { si_LK= "දැරණියගලට ඉහල අහසේ දඟකරන වලාපෙළ මවනා සොඳුරු දසුන රාත්‍රිය උදාවත් සමග ක්‍ෂයවේ."},
    { dv_IN= ""}]

# Display images and promotional banners
display_images = [ #OPTIONAL Display images and promotional banners
    { banner = ""},
    { small= ""},
    { thumbnail= ""},
    { medium = ""},
    { small= ""},
    { large = ""} ]


links = [ #OPTIONAL: External links and release channels
    { font_in_use = "" },
    { googlefonts = "" },
    { fontlibrary_org = "" },
    { typekit = "" } ]

########################################################################
# FONT BINARIES AND METADATA ###########################################
########################################################################

[[fonts]]
name = "" #REQUIERD
path = "" #OPTIONAL DEFUALTS to ./fonts/otf .fonts
style = "" #REQUIERD
weight = "" #REQUIERD
full_name = "" #OPTIONAL
preview_image = "" #OPTIONAL
protected = "" #OPTIONAL
purpose = "" #OPTIONAL
variable_font = "" #OPTIONAL
format = "" #REQUIERD
free = "" #REQUIERD

[[fonts]]
# ...

########################################################################
# APP OR PLATFOROM SPECIFIC CONFIGS AND DATA ###########################
########################################################################

# Additional metadata
[fontpackage.extras]
sinhala_font_level = 0

# Additional metadata to generate NPM packages
[fontpackage.npm]
# …

# Additional metadata to generate Appstram metadata files
[fontpackage.appstream]
# …
